<?php
/**
 * Author: HereNing
 *     __ __                _  __ _
 *    / // /___  ____ ___  / |/ /(_)___  ___ _
 *   / _  // -_)/ __// -_)/    // // _ \/ _ `/
 *  /_//_/ \__//_/   \__//_/|_//_//_//_/\_, /
 *                                     /___/
 * Date: 2018/12/8
 * Time: 11:32
 * Contact: herening@qq.com
 */

namespace app\common\base;

use think\Controller;

class FrontBase extends Controller{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}